<h1><center style='color:blue;'><u> NumPy 1D-2D Arrays</u></center></h1>

## 1D Array

In [11]:
import numpy as np
mylist = [78, 32, 12, 45, 8]
print(f'List elements: {mylist}')
myarray = np.array(mylist)
print(f'Array elements: {myarray}')
print(f'Shape: {myarray.shape}')
print(f'Max element: {myarray.max()}')
print(f'Min element: {myarray.min()}')
print(f'Mean/Average: {myarray.mean()}')
print(f'Max element index: {np.argmax(myarray)}')
print(f'Min element index: {np.argmin(myarray)}')
print(f'Last element: {myarray[-1]}')
print(f'Produit scalaire: {myarray*4}')

List elements: [78, 32, 12, 45, 8]
Array elements: [78 32 12 45  8]
Shape: (5,)
Max element: 78
Min element: 8
Mean/Average: 35.0
Max element index: 0
Min element index: 4
Last element: 8
Produit scalaire: [312 128  48 180  32]


## 2D-Array

In [33]:
# Define array and access its values
import numpy as np
mylist = [[1, 2, 3], [3, 4, 5]]
print(f'List elements:\n--------------\n{mylist}')
myarray = np.array(mylist)
print(f'Array elements:\n--------------\n{myarray}')
print(f'Shape: {myarray.shape}')
print(f'Matrix Transpose: {myarray.T}')
print(f'First row: {myarray[0]}')
print(f'Last row: {myarray[-1]}')
print(f'Specific row and col: {myarray[0, 2]}')
print('----------------------------')
mylist = [[1, 2, 3, 8], [3, 4, 5, 7], [12, 10, 8, 3], [41, 23, 14, 8]]
print(f'List elements:\n--------------\n{mylist}')
myarray = np.array(mylist)
print(f'Array elements:\n--------------\n{myarray}')
print(f'Specific rows and cols: {myarray[1 : , 0]}')
print(f'Specific rows and cols: {myarray[1 , 1:]}')

List elements:
--------------
[[1, 2, 3], [3, 4, 5]]
Array elements:
--------------
[[1 2 3]
 [3 4 5]]
Shape: (2, 3)
Matrix Transpose: [[1 3]
 [2 4]
 [3 5]]
First row: [1 2 3]
Last row: [3 4 5]
Specific row and col: 3
----------------------------
List elements:
--------------
[[1, 2, 3, 8], [3, 4, 5, 7], [12, 10, 8, 3], [41, 23, 14, 8]]
Array elements:
--------------
[[ 1  2  3  8]
 [ 3  4  5  7]
 [12 10  8  3]
 [41 23 14  8]]
Specific rows and cols: [ 3 12 41]
Specific rows and cols: [4 5 7]


## Series

In [41]:
# Series: a 1D-array of data where the rows are labeled using time axis
import numpy as np
import pandas as pd
mylist = [23, 19, 24, 16, 25]
rownames = ['Jan', 'Feb', 'Mar', 'Apr', 'May']
myarray = np.array(mylist)
myseries = pd.Series(myarray, index=rownames)
print(f'Series elements:\n{myseries}')
print(f'First element:{myseries[0]}')
print(f'First element:{myseries["Jan"]}')

Series elements:
Jan    23
Feb    19
Mar    24
Apr    16
May    25
dtype: int32
First element:23
First element:23


## Dataframe

In [53]:
# Dataframe: a multi-dimension array of data where the rows and cols can be labeled
import numpy as np
import pandas as pd
mylist = [[9, 10, 8], [8, 9, 5], [4, 7, 2]]
rownames = ['Fernand', 'Marc', 'Steve']
colnames = ['Note_1', 'Note_2', 'Note_3']
myarray = np.array(mylist)
mydataframe = pd.DataFrame(myarray, index=rownames, columns=colnames)
print(f'Dataframe elements:\n{mydataframe}')
print(f'First column:\n{mydataframe["Note_1"]}')
print(f'First column:\n{mydataframe.Note_1}')
print(f'Note_1 and Note_2 columns:\n{mydataframe[["Note_1", "Note_2"]]}')
print(mydataframe.iloc[0])
print(mydataframe.Note_3["Fernand"])

Dataframe elements:
         Note_1  Note_2  Note_3
Fernand       9      10       8
Marc          8       9       5
Steve         4       7       2
First column:
Fernand    9
Marc       8
Steve      4
Name: Note_1, dtype: int32
First column:
Fernand    9
Marc       8
Steve      4
Name: Note_1, dtype: int32
Note_1 and Note_2 columns:
         Note_1  Note_2
Fernand       9      10
Marc          8       9
Steve         4       7
Note_1     9
Note_2    10
Note_3     8
Name: Fernand, dtype: int32
8
